// Code generated by github.com/0B1t322/zero-validation, DO NOT EDIT.
package models

import (
    "github.com/0B1t322/zero-validaton/field"
    parsedPackage "github.com/0B1t322/zero-validation/example/some/internal/models"
    
)


type todoExtractor struct {
    ID field.StructField[parsedPackage.Todo,uint64]
    Name field.StructField[parsedPackage.Todo,string]
}

var ValidateTodo = todoExtractor{
    ID: field.NewField(
        "ID",
    nil,
        func(from parsedPackage.Todo) uint64 { return from.ID },
    ),
    Name: field.NewField(
        "Name",
    nil,
        func(from parsedPackage.Todo) string { return from.Name },
    ),
}
