// Code generated by github.com/0B1t322/zero-validation, DO NOT EDIT.
package model

import (
    "github.com/0B1t322/zero-validaton/field"
    
)


type createTasksInputItemExtractor struct {
    Name field.StructField[*CreateTasksInputItem,string]
    Description field.StructField[*CreateTasksInputItem,string]
    Status field.StructField[*CreateTasksInputItem,Status]
}

var ValidateCreateTasksInputItem = createTasksInputItemExtractor{
    Name: field.NewField(
        "Name",
    map[string]string{"json":"Name"},
        func(from *CreateTasksInputItem) string { return from.Name },
    ),
    Description: field.NewField(
        "Description",
    nil,
        func(from *CreateTasksInputItem) string { return from.Description },
    ),
    Status: field.NewField(
        "Status",
    nil,
        func(from *CreateTasksInputItem) Status { return from.Status },
    ),
}

type suggestTodosInputExtractor struct {
    Name field.StructField[*SuggestTodosInput,string]
}

var ValidateSuggestTodosInput = suggestTodosInputExtractor{
    Name: field.NewField(
        "Name",
    nil,
        func(from *SuggestTodosInput) string { return from.Name },
    ),
}
