// Code generated by github.com/0B1t322/zero-validation, DO NOT EDIT.
package model

import (
    "github.com/0B1t322/zero-validaton/field"
    "github.com/0B1t322/zero-validation/gqlgen-example/internal/model"
    
)


type createTasksInputExtractor struct {
    TodoID field.StructField[*CreateTasksInput,string]
    Tasks field.StructField[*CreateTasksInput,[]*model.CreateTasksInputItem]
}

var ValidateCreateTasksInput = createTasksInputExtractor{
    TodoID: field.NewField(
        "TodoID",
    map[string]string{"json":"TodoID"},
        func(from *CreateTasksInput) string { return from.TodoID },
    ),
    Tasks: field.NewField(
        "Tasks",
    map[string]string{"json":"Tasks"},
        func(from *CreateTasksInput) []*model.CreateTasksInputItem { return from.Tasks },
    ),
}

type createTodoInputExtractor struct {
    Name field.StructField[*CreateTodoInput,string]
    Description field.StructField[*CreateTodoInput,string]
}

var ValidateCreateTodoInput = createTodoInputExtractor{
    Name: field.NewField(
        "Name",
    map[string]string{"json":"Name"},
        func(from *CreateTodoInput) string { return from.Name },
    ),
    Description: field.NewField(
        "Description",
    map[string]string{"json":"Description"},
        func(from *CreateTodoInput) string { return from.Description },
    ),
}

type getTodosInputExtractor struct {
    IDs field.StructField[*GetTodosInput,[]string]
    TasksIDs field.StructField[*GetTodosInput,[]string]
}

var ValidateGetTodosInput = getTodosInputExtractor{
    IDs: field.NewField(
        "IDs",
    map[string]string{"json":"IDs"},
        func(from *GetTodosInput) []string { return from.IDs },
    ),
    TasksIDs: field.NewField(
        "TasksIDs",
    map[string]string{"json":"TasksIDs"},
        func(from *GetTodosInput) []string { return from.TasksIDs },
    ),
}
