// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/0B1t322/zero-validation/gqlgen-example/internal/model"
)

type CreateTasksInput struct {
	TodoID string                        `json:"TodoID"`
	Tasks  []*model.CreateTasksInputItem `json:"Tasks"`
}

type CreateTodoInput struct {
	Name        string `json:"Name"`
	Description string `json:"Description"`
}

type GetTodosInput struct {
	IDs      []string `json:"IDs,omitempty"`
	TasksIDs []string `json:"TasksIDs,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID          string       `json:"ID"`
	Name        string       `json:"Name"`
	Description string       `json:"Description"`
	Status      model.Status `json:"Status"`
}

type Todo struct {
	ID          string  `json:"ID"`
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Tasks       []*Task `json:"Tasks,omitempty"`
}
