// Code generated by github.com/0B1t322/zero-validation, DO NOT EDIT.
package todos

import (
	"github.com/0B1t322/zero-validaton/field"
	"github.com/0B1t322/zero-validation/grpc-example/pkg/api/external"
)

type createSomeRequest_InnerMessageExtractor struct {
	Some field.StructField[*CreateSomeRequest_InnerMessage, string]
}

var ValidateCreateSomeRequest_InnerMessage = createSomeRequest_InnerMessageExtractor{
	Some: field.NewField(
		"Some",
		map[string]string{"proto": "some", "json": "some"},
		func(from *CreateSomeRequest_InnerMessage) string { return from.Some },
	),
}

type createSomeRequestExtractor struct {
	BaseType       field.StructField[*CreateSomeRequest, uint64]
	BaseTypeArray  field.StructField[*CreateSomeRequest, []uint64]
	OptBaseType    field.StructField[*CreateSomeRequest, *uint64]
	RepeatedBytes  field.StructField[*CreateSomeRequest, [][]byte]
	Enum           field.StructField[*CreateSomeRequest, Enum]
	ExternalEnum   field.StructField[*CreateSomeRequest, external.Enum]
	Entity         field.StructField[*CreateSomeRequest, *Entity]
	Entities       field.StructField[*CreateSomeRequest, []*Entity]
	Enums          field.StructField[*CreateSomeRequest, []Enum]
	ExternalEnums  field.StructField[*CreateSomeRequest, []external.Enum]
	InnterMessage  field.StructField[*CreateSomeRequest, *CreateSomeRequest_InnerMessage]
	InnterMessages field.StructField[*CreateSomeRequest, []*CreateSomeRequest_InnerMessage]
	OneofExample   field.StructField[*CreateSomeRequest, isCreateSomeRequest_OneofExample]
	InnerEnum      field.StructField[*CreateSomeRequest, CreateSomeRequest_InnerEnum]
}

var ValidateCreateSomeRequest = createSomeRequestExtractor{
	BaseType: field.NewField(
		"BaseType",
		map[string]string{"json": "baseType", "proto": "base_type"},
		func(from *CreateSomeRequest) uint64 { return from.BaseType },
	),
	BaseTypeArray: field.NewField(
		"BaseTypeArray",
		map[string]string{"json": "baseTypeArray", "proto": "base_type_array"},
		func(from *CreateSomeRequest) []uint64 { return from.BaseTypeArray },
	),
	OptBaseType: field.NewField(
		"OptBaseType",
		map[string]string{"json": "optBaseType", "proto": "opt_base_type"},
		func(from *CreateSomeRequest) *uint64 { return from.OptBaseType },
	),
	RepeatedBytes: field.NewField(
		"RepeatedBytes",
		map[string]string{"json": "repeatedBytes", "proto": "repeated_bytes"},
		func(from *CreateSomeRequest) [][]byte { return from.RepeatedBytes },
	),
	Enum: field.NewField(
		"Enum",
		map[string]string{"json": "enum", "proto": "enum"},
		func(from *CreateSomeRequest) Enum { return from.Enum },
	),
	ExternalEnum: field.NewField(
		"ExternalEnum",
		map[string]string{"json": "externalEnum", "proto": "external_enum"},
		func(from *CreateSomeRequest) external.Enum { return from.ExternalEnum },
	),
	Entity: field.NewField(
		"Entity",
		map[string]string{"json": "entity", "proto": "entity"},
		func(from *CreateSomeRequest) *Entity { return from.Entity },
	),
	Entities: field.NewField(
		"Entities",
		map[string]string{"json": "entities", "proto": "entities"},
		func(from *CreateSomeRequest) []*Entity { return from.Entities },
	),
	Enums: field.NewField(
		"Enums",
		map[string]string{"json": "enums", "proto": "enums"},
		func(from *CreateSomeRequest) []Enum { return from.Enums },
	),
	ExternalEnums: field.NewField(
		"ExternalEnums",
		map[string]string{"json": "externalEnums", "proto": "external_enums"},
		func(from *CreateSomeRequest) []external.Enum { return from.ExternalEnums },
	),
	InnterMessage: field.NewField(
		"InnterMessage",
		map[string]string{"json": "innterMessage", "proto": "innter_message"},
		func(from *CreateSomeRequest) *CreateSomeRequest_InnerMessage { return from.InnterMessage },
	),
	InnterMessages: field.NewField(
		"InnterMessages",
		map[string]string{"json": "innterMessages", "proto": "innter_messages"},
		func(from *CreateSomeRequest) []*CreateSomeRequest_InnerMessage { return from.InnterMessages },
	),
	OneofExample: field.NewField(
		"OneofExample",
		nil,
		func(from *CreateSomeRequest) isCreateSomeRequest_OneofExample { return from.OneofExample },
	),
	InnerEnum: field.NewField(
		"InnerEnum",
		map[string]string{"proto": "inner_enum", "json": "innerEnum"},
		func(from *CreateSomeRequest) CreateSomeRequest_InnerEnum { return from.InnerEnum },
	),
}

type createSomeRequest_UintExtractor struct {
	Uint field.StructField[*CreateSomeRequest_Uint, uint64]
}

var ValidateCreateSomeRequest_Uint = createSomeRequest_UintExtractor{
	Uint: field.NewField(
		"Uint",
		map[string]string{"json": "uint", "proto": "uint"},
		func(from *CreateSomeRequest_Uint) uint64 { return from.Uint },
	),
}

type createSomeRequest_EnumTypeExtractor struct {
	EnumType field.StructField[*CreateSomeRequest_EnumType, Enum]
}

var ValidateCreateSomeRequest_EnumType = createSomeRequest_EnumTypeExtractor{
	EnumType: field.NewField(
		"EnumType",
		map[string]string{"json": "enumType", "proto": "enum_type"},
		func(from *CreateSomeRequest_EnumType) Enum { return from.EnumType },
	),
}

type createSomeRequest_InnerMessage_Extractor struct {
	InnerMessage field.StructField[*CreateSomeRequest_InnerMessage_, *CreateSomeRequest_InnerMessage]
}

var ValidateCreateSomeRequest_InnerMessage_ = createSomeRequest_InnerMessage_Extractor{
	InnerMessage: field.NewField(
		"InnerMessage",
		map[string]string{"json": "innerMessage", "proto": "inner_message"},
		func(from *CreateSomeRequest_InnerMessage_) *CreateSomeRequest_InnerMessage { return from.InnerMessage },
	),
}

type entityExtractor struct {
	Id field.StructField[*Entity, uint64]
}

var ValidateEntity = entityExtractor{
	Id: field.NewField(
		"Id",
		map[string]string{"json": "id", "proto": "id", "ru": "ID сущности"},
		func(from *Entity) uint64 { return from.Id },
	),
}
