// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type SearchTodosInput struct {
	Filter *SearchTodosInputFilter `json:"Filter"`
	Limit  int64                   `json:"Limit"`
}

type SearchTodosInputFilter struct {
	ByIDs  *SearchTodosInputFilterByIDs  `json:"ByIDs,omitempty"`
	ByName *SearchTodosInputFilterByName `json:"ByName,omitempty"`
}

type SearchTodosInputFilterByIDs struct {
	IDs []string `json:"IDs"`
}

type SearchTodosInputFilterByName struct {
	Name string `json:"Name"`
}

type SearchTodosResponse struct {
	Todos []*Todo `json:"Todos,omitempty"`
}

type Todo struct {
	ID string `json:"ID"`
}
