// Code generated by github.com/0B1t322/zero-validation v0.0.1, DO NOT EDIT.
package model

import (
    "github.com/0B1t322/zero-validation/field"
    
)




type searchTodosInputExtractor struct {
    Filter field.StructField[*SearchTodosInput,*SearchTodosInputFilter]
    Limit field.StructField[*SearchTodosInput,int64]
}

var ValidateSearchTodosInput = searchTodosInputExtractor{
    Filter: field.NewField(
        "Filter",
    map[string]string{"json":"Filter"},
        func(from *SearchTodosInput) *SearchTodosInputFilter { return from.Filter },
    ),
    Limit: field.NewField(
        "Limit",
    map[string]string{"json":"Limit"},
        func(from *SearchTodosInput) int64 { return from.Limit },
    ),
}

type searchTodosInputFilterExtractor struct {
    ByIDs field.StructField[*SearchTodosInputFilter,*SearchTodosInputFilterByIDs]
    ByName field.StructField[*SearchTodosInputFilter,*SearchTodosInputFilterByName]
}

var ValidateSearchTodosInputFilter = searchTodosInputFilterExtractor{
    ByIDs: field.NewField(
        "ByIDs",
    map[string]string{"json":"ByIDs"},
        func(from *SearchTodosInputFilter) *SearchTodosInputFilterByIDs { return from.ByIDs },
    ),
    ByName: field.NewField(
        "ByName",
    map[string]string{"json":"ByName"},
        func(from *SearchTodosInputFilter) *SearchTodosInputFilterByName { return from.ByName },
    ),
}

type searchTodosInputFilterByIDsExtractor struct {
    IDs field.StructField[*SearchTodosInputFilterByIDs,[]string]
}

var ValidateSearchTodosInputFilterByIDs = searchTodosInputFilterByIDsExtractor{
    IDs: field.NewField(
        "IDs",
    map[string]string{"json":"IDs"},
        func(from *SearchTodosInputFilterByIDs) []string { return from.IDs },
    ),
}

type searchTodosInputFilterByNameExtractor struct {
    Name field.StructField[*SearchTodosInputFilterByName,string]
}

var ValidateSearchTodosInputFilterByName = searchTodosInputFilterByNameExtractor{
    Name: field.NewField(
        "Name",
    map[string]string{"json":"Name"},
        func(from *SearchTodosInputFilterByName) string { return from.Name },
    ),
}





