// Code generated by github.com/0B1t322/zero-validation v0.0.1, DO NOT EDIT.
package todos

import (
	"github.com/0B1t322/zero-validation/field"
)

type IsSearchTodosRequest_Filter_By = isSearchTodosRequest_Filter_By

type searchTodosRequest_Filter_ByIDsExtractor struct {
	Ids field.StructField[*SearchTodosRequest_Filter_ByIDs, []uint64]
}

var ValidateSearchTodosRequest_Filter_ByIDs = searchTodosRequest_Filter_ByIDsExtractor{
	Ids: field.NewField(
		"Ids",
		map[string]string{"json": "ids", "proto": "ids", "ru": "Список ID"},
		func(from *SearchTodosRequest_Filter_ByIDs) []uint64 { return from.Ids },
	),
}

type searchTodosRequest_Filter_ByNameExtractor struct {
	Name field.StructField[*SearchTodosRequest_Filter_ByName, string]
}

var ValidateSearchTodosRequest_Filter_ByName = searchTodosRequest_Filter_ByNameExtractor{
	Name: field.NewField(
		"Name",
		map[string]string{"json": "name", "proto": "name", "ru": "Имя"},
		func(from *SearchTodosRequest_Filter_ByName) string { return from.Name },
	),
}

type searchTodosRequest_FilterExtractor struct {
	By field.StructField[*SearchTodosRequest_Filter, isSearchTodosRequest_Filter_By]
}

var ValidateSearchTodosRequest_Filter = searchTodosRequest_FilterExtractor{
	By: field.NewField(
		"By",
		nil,
		func(from *SearchTodosRequest_Filter) isSearchTodosRequest_Filter_By { return from.By },
	),
}

type searchTodosRequest_Filter_IdsExtractor struct {
	Ids field.StructField[*SearchTodosRequest_Filter_Ids, *SearchTodosRequest_Filter_ByIDs]
}

var ValidateSearchTodosRequest_Filter_Ids = searchTodosRequest_Filter_IdsExtractor{
	Ids: field.NewField(
		"Ids",
		map[string]string{"json": "ids", "proto": "ids", "ru": "Список ID"},
		func(from *SearchTodosRequest_Filter_Ids) *SearchTodosRequest_Filter_ByIDs { return from.Ids },
	),
}

type searchTodosRequest_Filter_ByName_Extractor struct {
	ByName field.StructField[*SearchTodosRequest_Filter_ByName_, *SearchTodosRequest_Filter_ByName]
}

var ValidateSearchTodosRequest_Filter_ByName_ = searchTodosRequest_Filter_ByName_Extractor{
	ByName: field.NewField(
		"ByName",
		map[string]string{"json": "byName", "proto": "by_name"},
		func(from *SearchTodosRequest_Filter_ByName_) *SearchTodosRequest_Filter_ByName { return from.ByName },
	),
}

type searchTodosRequestExtractor struct {
	Filter field.StructField[*SearchTodosRequest, *SearchTodosRequest_Filter]
	Limit  field.StructField[*SearchTodosRequest, uint64]
}

var ValidateSearchTodosRequest = searchTodosRequestExtractor{
	Filter: field.NewField(
		"Filter",
		map[string]string{"json": "filter", "proto": "filter", "ru": "Фильтр"},
		func(from *SearchTodosRequest) *SearchTodosRequest_Filter { return from.Filter },
	),
	Limit: field.NewField(
		"Limit",
		map[string]string{"json": "limit", "proto": "limit"},
		func(from *SearchTodosRequest) uint64 { return from.Limit },
	),
}
